"""ATT&CK Navigator layer export (Layer v4.5).

The Navigator layer is the analyst-facing view of the mapping: one heat-map
entry per technique, scored, coloured and commented. It is generated from the
same validated :class:`~engine.export.mitre_map.MITREMappingResult` as the
bundle and the OCSF findings — one producer, no second mapping path.

Layer format: https://github.com/mitre-attack/attack-navigator — Layer v4.5.
"""

from __future__ import annotations

import logging
from typing import Optional

from engine.export.attack_dataset import AttackDataset, default_dataset

logger = logging.getLogger(__name__)

LAYER_VERSION = "4.5"
NAVIGATOR_VERSION = "5.0.0"
DOMAIN = "enterprise-attack"

# Confidence -> score/colour. The gradient below mirrors these values.
_SCORE_BY_CONFIDENCE = {"high": 90, "medium": 60, "low": 30}
_COLOR_BY_CONFIDENCE = {"high": "#c0392b", "medium": "#e67e22", "low": "#f1c40f"}


def _technique_entry(technique: dict, dataset: AttackDataset) -> dict:
    technique_id = technique.get("subtechnique_id") or technique.get("technique_id") or ""
    confidence = str(technique.get("confidence", "medium")).lower()
    score = _SCORE_BY_CONFIDENCE.get(confidence, 50)
    color = _COLOR_BY_CONFIDENCE.get(confidence, "#f1c40f")

    record = dataset.get(technique_id)
    name = record.name if record else technique.get("technique_name", technique_id)
    comment_parts = [
        f"{technique.get('technique_id')} {technique.get('technique_name', '')}".strip(),
    ]
    if technique.get("subtechnique_id"):
        comment_parts.append(f"sub-technique: {technique_id} {name}")
    comment_parts.append(f"tactic: {technique.get('tactic', '')}")
    comment_parts.append(f"source: {technique.get('source', '')}")
    comment_parts.append(f"confidence: {confidence}")
    detection_ids = technique.get("detection_strategy_ids") or []
    if detection_ids:
        comment_parts.append("MITRE detection strategies: " + ", ".join(detection_ids[:6]))

    entry = {
        "techniqueID": technique_id,
        "score": score,
        "color": color,
        "comment": " | ".join(part for part in comment_parts if part),
        "enabled": True,
    }
    tactic_id = technique.get("tactic_id") or ""
    if tactic_id:
        entry["tactic"] = tactic_id
    return entry


def build_navigator_layer(
    *,
    mitre: Optional[dict] = None,
    sample_name: str = "",
    task_id: str = "",
    dataset: Optional[AttackDataset] = None,
) -> dict:
    """Build an ATT&CK Navigator Layer v4.5 document from a mapping result."""
    dataset = dataset or default_dataset()
    mitre = mitre or {}
    attack_version = str(mitre.get("attack_version") or dataset.version)

    techniques = [
        _technique_entry(technique, dataset)
        for technique in (mitre.get("techniques") or [])
    ]

    layer = {
        "name": f"HATCHERY — {sample_name}" if sample_name else "HATCHERY analysis",
        "versions": {
            "attack": attack_version,
            "navigator": NAVIGATOR_VERSION,
            "layer": LAYER_VERSION,
        },
        "domain": DOMAIN,
        "description": (
            "ATT&CK techniques mapped by HATCHERY from observed behaviour, capa, "
            "file-watch and YARA signals. Scores reflect mapping confidence, not "
            "event counts. Generated by HATCHERY; not an analyst-curated layer."
        ),
        "techniques": techniques,
        "gradient": {
            "colors": ["#f1c40f", "#e67e22", "#c0392b"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "high confidence", "color": "#c0392b"},
            {"label": "medium confidence", "color": "#e67e22"},
            {"label": "low confidence", "color": "#f1c40f"},
        ],
        "metadata": [
            {"name": "generated_by", "value": "HATCHERY"},
            {"name": "task_id", "value": task_id},
            {"name": "attack_version", "value": attack_version},
            {"name": "mapping_errors", "value": len(mitre.get("errors", []) or [])},
        ],
        "hideDisabled": False,
        "showTacticRowBackground": False,
    }
    logger.info(
        "Built ATT&CK Navigator layer v%s for ATT&CK %s with %d techniques",
        LAYER_VERSION, attack_version, len(techniques),
    )
    return layer


def validate_navigator_layer(layer: dict, dataset: Optional[AttackDataset] = None) -> list[str]:
    """Return every reason ``layer`` is not a valid Layer v4.5 document."""
    dataset = dataset or default_dataset()
    problems: list[str] = []

    for field_name in ("name", "versions", "domain", "techniques", "gradient"):
        if field_name not in layer:
            problems.append(f"missing required layer field {field_name!r}")

    versions = layer.get("versions") or {}
    if str(versions.get("layer")) != LAYER_VERSION:
        problems.append(f"versions.layer must be {LAYER_VERSION!r}")
    if str(versions.get("attack")) != dataset.version:
        problems.append(
            f"versions.attack {versions.get('attack')!r} does not match the pinned "
            f"dataset version {dataset.version!r}"
        )
    if layer.get("domain") != DOMAIN:
        problems.append(f"domain must be {DOMAIN!r}")

    techniques = layer.get("techniques")
    if not isinstance(techniques, list):
        problems.append("techniques must be a list")
        return problems

    for index, entry in enumerate(techniques):
        technique_id = entry.get("techniqueID")
        if not technique_id:
            problems.append(f"techniques[{index}] is missing techniqueID")
            continue
        if dataset.get(technique_id) is None:
            problems.append(
                f"techniques[{index}] id {technique_id!r} does not exist in the pinned dataset"
            )
        if not isinstance(entry.get("score"), int):
            problems.append(f"techniques[{index}] score must be an integer")
        if not entry.get("comment"):
            problems.append(f"techniques[{index}] must carry a comment")
        tactic = entry.get("tactic")
        if tactic and tactic not in (dataset.tactics_for(technique_id) or ()):
            problems.append(
                f"techniques[{index}] tactic {tactic!r} disagrees with the pinned dataset"
            )

    return problems


__all__ = [
    "LAYER_VERSION",
    "build_navigator_layer",
    "validate_navigator_layer",
]
